name: firstproject
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.9
  image_picker: ^1.1.0
  path: ^1.9.0
  intl: ^0.20.2
  provider: ^6.1.5
  flutter_spinkit: ^5.2.1
  date_field: ^6.0.3+1
  cupertino_icons: ^1.0.8
  lottie: ^2.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # version compatible avec Dart 3.8.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/
    - assets/lottie/construction.json


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

