// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl5Llj171P_6TyX-shIEoxrMSscunDiB0',
    appId: '1:983826481761:web:080ee9749d9e043cc12020',
    messagingSenderId: '983826481761',
    projectId: 'oleaone-beeeb',
    authDomain: 'oleaone-beeeb.firebaseapp.com',
    storageBucket: 'oleaone-beeeb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCDP2LHQ2vjj1Gz_gQIOdUe9O9yq9siv0',
    appId: '1:983826481761:android:1c23a495f95c66a5c12020',
    messagingSenderId: '983826481761',
    projectId: 'oleaone-beeeb',
    storageBucket: 'oleaone-beeeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbjPNhogsxYQA9uYAn5qCbfsDLLo3Win8',
    appId: '1:983826481761:ios:6bb538c9e7b1cb4fc12020',
    messagingSenderId: '983826481761',
    projectId: 'oleaone-beeeb',
    storageBucket: 'oleaone-beeeb.firebasestorage.app',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl5Llj171P_6TyX-shIEoxrMSscunDiB0',
    appId: '1:983826481761:web:1ddfc26340ea3db9c12020',
    messagingSenderId: '983826481761',
    projectId: 'oleaone-beeeb',
    authDomain: 'oleaone-beeeb.firebaseapp.com',
    storageBucket: 'oleaone-beeeb.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbjPNhogsxYQA9uYAn5qCbfsDLLo3Win8',
    appId: '1:983826481761:ios:6bb538c9e7b1cb4fc12020',
    messagingSenderId: '983826481761',
    projectId: 'oleaone-beeeb',
    storageBucket: 'oleaone-beeeb.firebasestorage.app',
    iosBundleId: 'com.example.firstproject',
  );

}